# Generated by Django 5.0.4 on 2024-08-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_consulta_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patologia',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AddField(
            model_name='patologia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='patologia_imagenes/'),
        ),
    ]
