# Generated by Django 5.0.4 on 2024-10-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_numeros_farmacia'),
    ]

    operations = [
        migrations.AddField(
            model_name='patologia',
            name='diagnostico',
            field=models.CharField(choices=[('Con diagnóstico', 'Sin diagnóstico')], default='Con diagnóstico', max_length=30),
        ),
    ]
