# Generated by Django 5.0.4 on 2024-10-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_patologia_diagnostico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patologia',
            name='diagnostico',
            field=models.CharField(choices=[('Con diagnóstico', 'Con diagnóstico'), ('Sin diagnóstico', 'Sin diagnóstico')], default='Con diagnóstico', max_length=30),
        ),
    ]
